  # Play to define a variable and then call it into the with_items loop
- hosts: R1
  gather_facts: false
  connection: network_cli

  vars:
    loopback:
      15: 15.15.15.15
      16: 16.16.16.16



  tasks:
    - name: create loopbacks and assign IP addresses
      cisco.ios.ios_config:
        lines: ip address {{item.value}} 255.255.255.255
        parents: interface loopback {{item.key}}
      with_dict: "{{new_loopback}}"

# Create the Dict in a folder named group_vars and create a play to call that file in the play
- hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:
    - name: create loopbacks and assign IP addresses
      cisco.ios.ios_config:
        lines:
         - ip vrf forwarding A
         - ip address {{item.value}} 255.255.255.255
        parents: interface loopback {{item.key}}
      with_dict: "{{new_loopback}}"

    - name: see the new interfaces
      cisco.ios.ios_command:
        commands: show ip int brief
      register: output

    - name: print to screen
      debug:
        var=output.stdout_lines
